export const typeIconMap = {
  beach: "🏖️",
  city: "🌆",
  culture: "🏛️",
  nature: "🌄",
  luxury: "✨",
  heritage: "🕌",
};

export const destinations = [
  {
    id: "paris",
    name: "Paris",
    country: "France",
    description: "Romantic city with art, cafes and iconic landmarks.",
    vibes: ["romantic", "culture"],
    budgetLevel: "medium",
    daysMin: 3,
    daysMax: 5,
    popularityScore: 95,
    badge: "Popular",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200",
  },
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    description: "Relaxing beaches, temples and tropical vibes.",
    vibes: ["beach", "nature"],
    budgetLevel: "medium",
    daysMin: 5,
    daysMax: 7,
    popularityScore: 90,
    badge: "Trending",
    image:
      "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=1200",
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    description: "Ancient history, architecture and Italian food.",
    vibes: ["heritage", "culture"],
    budgetLevel: "medium",
    daysMin: 3,
    daysMax: 5,
    popularityScore: 92,
    badge: "Popular",
    image:
      "https://images.unsplash.com/photo-1520175480921-4edfa2983e0f?w=1200",
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    description: "Modern city blended with tradition and technology.",
    vibes: ["city", "modern"],
    budgetLevel: "high",
    daysMin: 5,
    daysMax: 7,
    popularityScore: 94,
    badge: "Popular",
    image:
      "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1200",
  },
  {
    id: "dubai",
    name: "Dubai",
    country: "UAE",
    description: "Luxury shopping, skyscrapers and desert adventures.",
    vibes: ["luxury", "city"],
    budgetLevel: "high",
    daysMin: 3,
    daysMax: 5,
    popularityScore: 91,
    badge: "Luxury",
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200",
  },
  {
    id: "goa",
    name: "Goa",
    country: "India",
    description: "Laid-back beaches, nightlife and weekend vibes.",
    vibes: ["beach", "budget"],
    budgetLevel: "low",
    daysMin: 2,
    daysMax: 3,
    popularityScore: 88,
    badge: "Budget",
    image:
      "https://images.unsplash.com/photo-1587922546307-776227941871?w=1200",
  },
  {
    id: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    description: "Street food, nightlife and vibrant city life.",
    vibes: ["city", "budget"],
    budgetLevel: "low",
    daysMin: 3,
    daysMax: 5,
    popularityScore: 89,
    badge: "Budget",
    image:
      "https://images.unsplash.com/photo-1504512485720-7d83a16ee930?w=1200",
  },
  {
    id: "newyork",
    name: "New York",
    country: "USA",
    description: "Fast-paced city with iconic sights and culture.",
    vibes: ["city", "culture"],
    budgetLevel: "high",
    daysMin: 5,
    daysMax: 7,
    popularityScore: 96,
    badge: "Popular",
    image:
      "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200",
  },
  {
    id: "jaipur",
    name: "Jaipur",
    country: "India",
    description: "Royal palaces, forts and rich heritage.",
    vibes: ["heritage", "culture"],
    budgetLevel: "low",
    daysMin: 2,
    daysMax: 3,
    popularityScore: 85,
    badge: "Budget",
    image:
      "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=1200",
  },
  {
    id: "maldives",
    name: "Maldives",
    country: "Maldives",
    description: "Overwater villas and crystal-clear waters.",
    vibes: ["luxury", "romantic", "beach"],
    budgetLevel: "high",
    daysMin: 5,
    daysMax: 7,
    popularityScore: 93,
    badge: "Luxury",
    image: "https://images.unsplash.com/photo-1540202404-1b927e27fa8b?w=1200",
  },
];
